server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking
    username: root
    password: Manh2004

  jpa:
    hibernate:
      ddl-auto: update
    #      none, upadate, autp-update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type:
              - authorization_code
              - password
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenmanhlc10@gmail.com
    password: qrgd bqwc wlcu foti
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
jwt:
  key: YlAkN0BpWV5rMXgmOXpRIVdkTjRBKkpAcDNYdkYjbw==